AWSTemplateFormatVersion: 2010-09-09
Description: Deploy System's VPC with Ingress route
#----------------------------------------------
Parameters:
  #------------------
  VpcName:
    Description: Name for the VPC
    Type: String
    Default: NwfwPoC-SystemAVpc
    ConstraintDescription: Can contain only ASCII characters.
  VpcCidr:
    Description: CIDR Block for the VPC
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.1.2.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.0.0/16
  VpcCidrForIngress:
    Description: CIDR Block for the VPC's Ingress subnets
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 100.64.0.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.0.0/16
  DnsSupport:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DnsHostnames:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  #---
  DhcpOptionsDomainNameServers1:
    Description: "The IPv4 addresses of a 1st domain name servers, or AmazonProvidedDNS"
    Type: String
    Default: "AmazonProvidedDNS"
  DhcpOptionsDomainNameServers2:
    Description: "The IPv4 addresses of a 2nd domain name servers, or Blank"
    Type: String
    Default: ""
  DhcpOptionsNtpServers1:
    Description: "The IPv4 addresses of a 1st Network Time Protocol (NTP) servers."
    Type: String
    Default: 169.254.169.123
  DhcpOptionsNtpServers2:
    Description: "The IPv4 addresses of a 2nd Network Time Protocol (NTP) servers or blank."
    Type: String
    Default: ""
  #---
  FwSubnet1Name:
    Description: Name for the Firewall Subnet 1
    Type: String
    Default: FwSub1
  FwSubnet1Cidr:
    Description: CIDR Block for the Firewall subnet 1
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 100.64.0.192/28
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  FwSubnet2Name:
    Description: Name for the Firewall Subnet 2
    Type: String
    Default: FwSub2
  FwSubnet2Cidr:
    Description: CIDR Block for the Firewall subnet 2
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 100.64.0.208/28
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  FwSubnet3Name:
    Description: Name for the Firewall Subnet 3
    Type: String
    Default: FwSub3
  FwSubnet3Cidr:
    Description: CIDR Block for the Firewall subnet 3
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 100.64.0.224/28
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  ElbSubnet1Name:
    Description: Name for the Nat Subnet 1
    Type: String
    Default: ElbSub1
  ElbSubnet1Cidr:
    Description: CIDR Block for the Nat subnet 1
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 100.64.0.0/27
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  ElbSubnet2Name:
    Description: Name for the Nat Subnet 2
    Type: String
    Default: ElbSub2
  ElbSubnet2Cidr:
    Description: CIDR Block for the Nat subnet 2
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 100.64.0.32/27
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  ElbSubnet3Name:
    Description: Name for the Nat Subnet 3
    Type: String
    Default: ElbSub3
  ElbSubnet3Cidr:
    Description: CIDR Block for the Nat subnet 3
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 100.64.0.64/27
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  TgwSubnet1Name:
    Description: Name for the TransitGateway Subnet 1
    Type: String
    Default: TgwSub1
  TgwSubnet1Cidr:
    Description: CIDR Block for the TransitGateway subnet 1
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.1.2.192/28
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  ResourceSubnet1Name:
    Description: Name for the Resuces Subnet 1
    Type: String
    Default: ResourceSub1
  ResourceSubnet1Cidr:
    Description: CIDR Block for the Resuces subnet 1
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.1.2.0/26
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  #---
  ResourceSubnet2Name:
    Description: Name for the Resuces Subnet 2
    Type: String
    Default: ResourceSub2
  ResourceSubnet2Cidr:
    Description: CIDR Block for the Resuces subnet 2
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.1.2.64/26
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  #---
  ResourceSubnet3Name:
    Description: Name for the Resuces Subnet 3
    Type: String
    Default: ResourceSub3
  ResourceSubnet3Cidr:
    Description: CIDR Block for the Resuces subnet 3
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.1.2.128/26
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  #---
  TgwSubnet2Name:
    Description: Name for the TransitGateway Subnet 2
    Type: String
    Default: TgwSub2
  TgwSubnet2Cidr:
    Description: CIDR Block for the TransitGateway subnet 2
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.1.2.208/28
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #---
  TgwSubnet3Name:
    Description: Name for the TransitGateway Subnet 3
    Type: String
    Default: TgwSub3
  TgwSubnet3Cidr:
    Description: CIDR Block for the TransitGateway subnet 3
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.1.2.224/28
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be like 10.1.1.0/24
  #------------------
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      -
        Label:
          default: "VPC Configurations"
        Parameters:
          - VpcName
          - VpcCidr
          - VpcCidrForIngress
          - DnsSupport
          - DnsHostnames
      -
        Label:
          default: "VPC DHCP Options Configurations"
        Parameters:
          - DhcpOptionsDomainNameServers1
          - DhcpOptionsDomainNameServers2
          - DhcpOptionsNtpServers1
          - DhcpOptionsNtpServers2
      -
        Label:
          default: "Subnets Configurations"
        Parameters:
          - FwSubnet1Name
          - FwSubnet1Cidr
          - FwSubnet2Name
          - FwSubnet2Cidr
          - FwSubnet3Name
          - FwSubnet3Cidr
          - ElbSubnet1Name
          - ElbSubnet1Cidr
          - ElbSubnet2Name
          - ElbSubnet2Cidr
          - ElbSubnet3Name
          - ElbSubnet3Cidr
          - ResourceSubnet1Name
          - ResourceSubnet1Cidr
          - ResourceSubnet2Name
          - ResourceSubnet2Cidr
          - ResourceSubnet3Name
          - ResourceSubnet3Cidr
          - TgwSubnet1Name
          - TgwSubnet1Cidr
          - TgwSubnet2Name
          - TgwSubnet2Cidr
          - TgwSubnet3Name
          - TgwSubnet3Cidr
#----------------------------------------------
Resources:
  #------------------ VPC FlowLog Role
  FlowlogRole:
    Type: "AWS::IAM::Role"
    Properties: 
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - vpc-flow-logs.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: "Flowlog"
          PolicyDocument:
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: 
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                  - "logs:PutLogEvents"
                Resource: "*"
  #------------------ VPC
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: !Ref DnsSupport
      EnableDnsHostnames: !Ref DnsHostnames
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}
  AddIngressCidrToVpc:
    Type: AWS::EC2::VPCCidrBlock
    Properties: 
      CidrBlock: !Ref VpcCidrForIngress
      VpcId: !Ref Vpc
  #------------------ DHCP Options
  DhcpOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainNameServers:
        - !Ref DhcpOptionsDomainNameServers1
        - !Ref DhcpOptionsDomainNameServers2
      NtpServers: 
        - !Ref DhcpOptionsNtpServers1
        - !Ref DhcpOptionsNtpServers2
      Tags: 
        - Key: Name
          Value: NwfwPoC-OutboundVpc-DhcpOptions
  AssociationDhcpOptionsToVpc:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      DhcpOptionsId: !Ref DhcpOptions
      VpcId: !Ref Vpc
  #------------------ Internet GW
  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: NwfwPoC-OutboundVpc-Igw
  AttachIgw:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref Igw
      VpcId: !Ref Vpc
  #------------------ Subnet
  #-- Firewall Subnets
  FwSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn:
      - AddIngressCidrToVpc
    Properties:
      CidrBlock: !Ref FwSubnet1Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 0
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${FwSubnet1Name}
  FwSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn:
      - AddIngressCidrToVpc
    Properties:
      CidrBlock: !Ref FwSubnet2Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 1
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${FwSubnet2Name}
  FwSubnet3:
    Type: AWS::EC2::Subnet
    DependsOn:
      - AddIngressCidrToVpc
    Properties:
      CidrBlock: !Ref FwSubnet3Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 2
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${FwSubnet3Name}
  #-- Nat Subnets
  ElbSubnet1:
    Type: AWS::EC2::Subnet
    DependsOn:
      - AddIngressCidrToVpc
    Properties:
      CidrBlock: !Ref ElbSubnet1Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 0
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${ElbSubnet1Name}
  ElbSubnet2:
    Type: AWS::EC2::Subnet
    DependsOn:
      - AddIngressCidrToVpc
    Properties:
      CidrBlock: !Ref ElbSubnet2Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 1
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${ElbSubnet2Name}
  ElbSubnet3:
    Type: AWS::EC2::Subnet
    DependsOn:
      - AddIngressCidrToVpc
    Properties:
      CidrBlock: !Ref ElbSubnet3Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 2
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${ElbSubnet3Name}
  #-- Resouce Subnets
  ResourceSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref ResourceSubnet1Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 0
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${ResourceSubnet1Name}
  ResourceSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref ResourceSubnet2Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 1
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${ResourceSubnet2Name}
  ResourceSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref ResourceSubnet3Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 2
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${ResourceSubnet3Name}
  #-- Tgw Subnets
  TgwSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref TgwSubnet1Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 0
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${TgwSubnet1Name}
  TgwSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref TgwSubnet2Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 1
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${TgwSubnet2Name}
  TgwSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref TgwSubnet3Cidr
      VpcId: !Ref Vpc
      AvailabilityZone: !Select
      - 2
      - Fn::GetAZs: !Ref 'AWS::Region'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${VpcName}-${TgwSubnet3Name}
